using System.Net;
using AzureConnectivityDoctor.Core.AzureAssessment;
using AzureConnectivityDoctor.Core.Identity;
using AzureConnectivityDoctor.Core.Model;
using AzureConnectivityDoctor.Core.Probes;

namespace AzureConnectivityDoctor.Core.Tests.Fakes;

/// <summary>
/// Hand-written stubs for every probe interface.
/// </summary>
/// <remarks>
/// Stubs are written by hand rather than generated by a mocking framework. The interfaces are
/// small, the stubs are readable by someone who has never used a .NET mocking library, and the
/// test project keeps one fewer dependency.
/// </remarks>
internal sealed class StubDnsProbe : IDnsProbe
{
    internal StubDnsProbe(DnsProbeResult result)
    {
        Result = result;
    }

    internal DnsProbeResult Result { get; }

    internal int CallCount { get; private set; }

    public Task<DnsProbeResult> ResolveAsync(
        ProbeTarget target,
        TimeSpan timeout,
        CancellationToken cancellationToken)
    {
        CallCount++;
        return Task.FromResult(Result);
    }
}

internal sealed class StubTcpProbe : ITcpProbe
{
    internal StubTcpProbe(TcpProbeResult result)
    {
        Result = result;
    }

    internal TcpProbeResult Result { get; }

    internal int CallCount { get; private set; }

    public Task<TcpProbeResult> ConnectAsync(
        ProbeTarget target,
        IReadOnlyList<IPAddress> addresses,
        TimeSpan timeout,
        CancellationToken cancellationToken)
    {
        CallCount++;
        return Task.FromResult(Result);
    }
}

internal sealed class StubTlsProbe : ITlsProbe
{
    internal StubTlsProbe(TlsProbeResult result)
    {
        Result = result;
    }

    internal TlsProbeResult Result { get; }

    internal int CallCount { get; private set; }

    public Task<TlsProbeResult> HandshakeAsync(
        ProbeTarget target,
        IPAddress address,
        TimeSpan timeout,
        CancellationToken cancellationToken)
    {
        CallCount++;
        return Task.FromResult(Result);
    }
}

internal sealed class StubHttpProbe : IHttpProbe
{
    internal StubHttpProbe(StageResult result)
    {
        Result = result;
    }

    internal StageResult Result { get; }

    internal int CallCount { get; private set; }

    public Task<StageResult> SendAsync(ProbeTarget target, TimeSpan timeout, CancellationToken cancellationToken)
    {
        CallCount++;
        return Task.FromResult(Result);
    }
}

internal sealed class StubTokenProbe : ITokenProbe
{
    internal StubTokenProbe(TokenProbeResult result)
    {
        Result = result;
    }

    internal TokenProbeResult Result { get; }

    internal int CallCount { get; private set; }

    public Task<TokenProbeResult> AcquireAsync(string scope, CancellationToken cancellationToken)
    {
        CallCount++;
        LastScope = scope;
        return Task.FromResult(Result);
    }

    internal string? LastScope { get; private set; }
}

internal sealed class StubSqlProbe : ISqlProbe
{
    internal StubSqlProbe(StageResult result)
    {
        Result = result;
    }

    internal StageResult Result { get; }

    internal int CallCount { get; private set; }

    public Task<StageResult> ProbeAsync(
        ProbeTarget target,
        string? accessToken,
        TimeSpan timeout,
        CancellationToken cancellationToken)
    {
        CallCount++;
        return Task.FromResult(Result);
    }
}

internal sealed class StubServiceBusProbe : IServiceBusProbe
{
    internal StubServiceBusProbe(StageResult result)
    {
        Result = result;
    }

    internal StageResult Result { get; }

    internal int CallCount { get; private set; }

    public Task<StageResult> ProbeAsync(
        ProbeTarget target,
        bool useWebSockets,
        TimeSpan timeout,
        CancellationToken cancellationToken)
    {
        CallCount++;
        return Task.FromResult(Result);
    }
}

internal sealed class StubAzureAssessor : IAzureAssessor
{
    internal StubAzureAssessor(StageResult result)
    {
        Result = result;
    }

    internal StageResult Result { get; }

    internal int CallCount { get; private set; }

    public Task<StageResult> AssessAsync(string resourceId, CancellationToken cancellationToken)
    {
        CallCount++;
        return Task.FromResult(Result);
    }
}
